wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727594400.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.19
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
epochs:
  desc: null
  value: 400
noise_lev:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0005
save_checkpoint:
  desc: null
  value: true
